Alisher/invoice entity
ilmhub-uz/invoice pull request #40
Opened 2022-02-08 13:05 UTC by AlisherDe

## Invoice.cs
## InvoiceItem.cs
### AppDbContext.cs
### DbSet<Invoice> DbSet<Invoice>
#### Create Relationships

2022-02-08 16:16 UTC, wahid-d requested changes

2022-02-08 16:16 UTC, wahid-d commented on webapp/appsettings.json
> +        "DefaultConnection": "server=localhost; user id=SA;pwd=alisher1991@@;database=invoice;"
clean this

2022-02-08 16:51 UTC, AlisherDe commented on webapp/appsettings.json
> +        "DefaultConnection": "server=localhost; user id=SA;pwd=alisher1991@@;database=invoice;"
clean

2022-02-09 07:36 UTC, wahid-d approved these changes

2022-02-09 07:37 UTC, merged