minor
ilmhub-uz/invoice pull request #41
Opened 2022-02-08 14:57 UTC by Xakimov1610

Ustoz shu joygach to'g'ri ketvomanmi yo'nalish bervorin

2022-02-08 21:34 UTC, Xakimov1610 commented
<img width="1092" alt="Screen Shot 2022-02-09 at 02 29 27" src="https://user-images.githubusercontent.com/68727555/153079369-0928b77b-a48c-4da6-8304-f963b8e87df9.png">
<img width="983" alt="Screen Shot 2022-02-09 at 02 29 46" src="https://user-images.githubusercontent.com/68727555/153079439-f155686f-0c1d-484d-9127-ffc24de85d14.png">

2022-02-09 08:29 UTC, wahid-d requested changes

2022-02-09 08:29 UTC, wahid-d commented on webapp/appsettings.json
> +        "SeedOrganization":
Organizations deb nomlang

2022-02-09 08:29 UTC, wahid-d commented on webapp/appsettings.json
> +        "SeedOrganization":
Bu ma'lumotlar PR da ko'rinmasligi kerak

2022-02-09 08:29 UTC, wahid-d commented on webapp/appsettings.json
> +        "DefaultConnection": "Server=localhost; Database=webapp; User Id=SA; PWD=miras2019!"
Connection String qiymatini ham PR dan o'chiring

2022-02-09 08:29 UTC, wahid-d commented on webapp/Seed.cs
> +public class SeedOrganization
Organization

2022-02-09 08:29 UTC, wahid-d commented on webapp/Seed.cs
> +        if(seedData)
Hammasini if ichiga olish orniga:
```cs
if(!seedData)
{
     _logger.LogInformation("Seeding database is disabled. Cancelling Seed.cs service...");
     return Task.Completed;
}
```
// bu yerdan qolgan taqur tuqur kodlarni yozasiz

2022-02-09 08:29 UTC, wahid-d commented on webapp/Seed.cs
> +                    await _roleM.CreateAsync(new IdentityRole<Guid>(role));
Role create qilgandan keyin Log qiling

2022-02-09 08:29 UTC, wahid-d commented on webapp/Seed.cs
> +            });
Logika hato. Birdan ortiq organization seed qilmoqchi bo'lsachi? U ham list bo'lishi kerak User kabi.

2022-02-14 14:37 UTC, closed without merging